# arxivの学問領域の指定
subject: 'cat:cs.* OR cat:eess.* OR cat:econ.*'

# 検索キーワード
keywords:
        satellite: 5
        aerial: 5
        kaggle: 4
        impact evaluation: 3
        AI: 3

# 通知の閾値
score_threshold: 0
